[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fancoin = "6GJQt9Rbz1BJBmKDPq9KgR2ThEtFtp47dJ9EnZ7Qdnhq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
target = "bpfel-unknown-none"
toolchain = "nightly"